const actionTypes = {
    SEARCH: 'SEARCH',
    SEARCH_PENDING: 'SEARCH_PENDING',
    SEARCH_FULFILLED: 'SEARCH_FULFILLED',
    SEARCH_REJECTED: 'SEARCH_REJECTED',

    SET_ACTIVE_ROUTE: 'SET_ACTIVE_ROUTE',
    SET_ACTIVE_ROUTE_FULFILLED: 'SET_ACTIVE_ROUTE_FULFILLED',
};

export default actionTypes;
